- name: create  and groups 
  hosts: server2
  vars:
    password: 
  tasks:
    - name: create groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - Sales
        - Support
        - Services
        - IT

    - name: create sale users
      ansible.builtin.user:
        name: "{{ item }}"
        group: Sales
        state: present
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
        - Frank
        - Annabelle
    
    - name: create support users
      ansible.builtin.user:
        name: "{{ item }}"
        group: Support
        state: present
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
        - Carl
        - Dyson
        - Gerry

    - name: create services users
      ansible.builtin.user:
        name: "{{ item }}"
        group: Services
        state: present
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
        - Jameson
        - Isabella
    - name: create IT users
      ansible.builtin.user:
        name: "{{ item }}"
        group: IT
        state: present
        password: "{{ '@#FD12' | password_hash('sha512') }}"
      loop:
          - Harold
          - Evert
          - Bob
    - name: set SSH key for users
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN90Xtfjxqs2ZpO0VqR1jr92mJiTx3IaEl/F+LiOZJK
        validate_certs: false
      loop: 
        - Frank
        - Annabelle
        - Carl
        - Dyson
        - Gerry
        - Jameson
        - Isabella
        - Harold
        - Evert
        - Bob












